spring:
  datasource:
    username: postgres
    password: 123
    url: 'jdbc:postgresql://localhost:5432/migration?currentSchema=sb_flyway'
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: 'jdbc:postgresql://localhost:5432/migration'
    user: postgres
    password: 123
    default-schema: sb_flyway