spring:
  cache:
    basepath: 'dev.jlkeesh.springadvanced'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~
    username: sa
    password: sa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true