spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true