spring:
  datasource:
    username: postgres
    password: 123
    url: 'jdbc:postgresql://localhost:5432/migration?currentSchema=liquibase'
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog/db.changelog-master.xml'