spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: sa
    password: sa
    url: 'jdbc:h2:file:./post_db'
    driver-class-name: org.h2.Driver
server:
  port: 9090
comments:
  service:
    base.url: 'http://localhost:8080/api/comments'

